server:
  forward-headers-strategy: framework

  error:
    include-message: always

  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    generate-ddl: true
    ddl-auto: update
    open-in-view: true

springdoc.swagger-ui.path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

social-media:
  facebook:
    url: https://www.facebook.com/sharer/sharer.php
    icon: https://www.facebook.com/icon
  twitter:
    url: https://twitter.com/intent/tweet
    icon: https://twitter.com/icon
